### ISSUE TITLE
Position of right column changes based on width of quote text.

### ISSUE THREAD

**Issue by thinsoldier** [tommygebru/weather#2]
When the quote text is short like "you pass butter" the right column is far from the right edge of the viewport. 

When the quote is longer like "Break the cycle, Morty. Rise above! Focus on science." the right column is all the way to the right.

**Comment by tommygebru** [comment]
I will address this issue... side note, these recent github issues belong under the quote page not weather 👍

**Comment by thinsoldier** [comment]
crap, forgot which tab i was looking at
